version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0

  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ".:/app:delegated"

  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      - ".:/var/www:delegated"
    depends_on:
      - "app"

networks:
  default:
    name: 'tourguide'
